// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXUx80O2frtDSEpPRGUKRKtWMjvTF--O4',
    appId: '1:10961592997:web:7824b50b01d1a54fce234c',
    messagingSenderId: '10961592997',
    projectId: 'basic-app-a6436',
    authDomain: 'basic-app-a6436.firebaseapp.com',
    storageBucket: 'basic-app-a6436.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDRnEmUldEvL6fjcwVvlbXJT5CQZpKgzlo',
    appId: '1:10961592997:android:719979a6a6be76c8ce234c',
    messagingSenderId: '10961592997',
    projectId: 'basic-app-a6436',
    storageBucket: 'basic-app-a6436.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjOZa-L-UN2xcCkvITu0TLrI1Jp1AMrL8',
    appId: '1:10961592997:ios:f148142423f2e166ce234c',
    messagingSenderId: '10961592997',
    projectId: 'basic-app-a6436',
    storageBucket: 'basic-app-a6436.appspot.com',
    iosBundleId: 'com.example.flutternewclass',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjOZa-L-UN2xcCkvITu0TLrI1Jp1AMrL8',
    appId: '1:10961592997:ios:f148142423f2e166ce234c',
    messagingSenderId: '10961592997',
    projectId: 'basic-app-a6436',
    storageBucket: 'basic-app-a6436.appspot.com',
    iosBundleId: 'com.example.flutternewclass',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAXUx80O2frtDSEpPRGUKRKtWMjvTF--O4',
    appId: '1:10961592997:web:b0664ff75a6adcface234c',
    messagingSenderId: '10961592997',
    projectId: 'basic-app-a6436',
    authDomain: 'basic-app-a6436.firebaseapp.com',
    storageBucket: 'basic-app-a6436.appspot.com',
  );

}